server:
  port: 8080
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-event-catalog-service
          uri: lb://ms-event-catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog/(?<segment>.*), /api/v1/$\{segment}
        - id: user-service
          uri: lb://ms-user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /api/v1/user/$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
